# These are supported funding model platforms

github: # Se você tiver GitHub Sponsors ativado, coloque seu usuário aqui: [wandersonstt]
patreon: # Se tiver Patreon
open_collective: # Se tiver Open Collective
ko_fi: # Se tiver Ko-fi
tidelift: # Se tiver Tidelift
community_bridge: # Se tiver
liberapay: # Se tiver
issuehunt: # Se tiver
lfx_crowdfunding: # Se tiver
polar: # Se tiver
buy_me_a_coffee: # Se tiver
thanks_dev: # Se tiver

# AQUI É O IMPORTANTE PARA O LIVEPIX:
custom: ["https://livepix.gg/alho97"]
