<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <FileVersion>2.0.1.0</FileVersion>
    <AssemblyVersion>2.0.1.0</AssemblyVersion>
    <ApplicationIcon>youtube.ico</ApplicationIcon>
    <PackageIcon>youtube.ico</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="youtube.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AngleSharp" Version="1.8.0-beta.603" />
    <PackageReference Include="Autoupdater.NET.Official" Version="1.9.3" />
    <PackageReference Include="CliWrap" Version="3.10.5" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4181-prerelease" />
    <PackageReference Include="YoutubeExplode" Version="6.6.1" />
    <PackageReference Include="YoutubeExplode.Converter" Version="6.6.1" />
  </ItemGroup>

  <ItemGroup>
    <None Update="LICENSE.txt">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="youtube.ico">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <None Include=".github\FUNDING.yml" />
  </ItemGroup>

</Project>